site_name: QQMusicApi
site_description: 使用 Python 编写的用于调用 QQ音乐 各种 API 的库.

theme:
  name: "material"
  language: zh
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: lucide/sun-moon
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/weather-night
      name: 切换到深色模式
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: 切换到浅色模式
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - toc.follow

repo_name: l-1124/QQMusicApi
repo_url: https://github.com/l-1124/QQMusicApi
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/l-1124/QQMusicApi

markdown_extensions:
  - nl2br
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - markdown_callouts.github_callouts
  - toc
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.definition
  - pymdownx.blocks.tab:
      alternate_style: True
      combine_header_slug: True
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      url_download: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:

plugins:
  - search:
      lang: zh
  - mkdocstrings:
      handlers:
        python:
          paths: [., qqmusic_api]
          load_external_modules: true
          options:
            members_order: source
            separate_signature: true
            group_by_category: false
            show_root_heading: true
            show_symbol_type_heading: true
            heading_level: 1
            filters: ["!^_"]
            show_signature_annotations: true
            signature_crossrefs: true
            merge_init_into_class: true
            docstring_section_style: spacy
          inventories:
            - https://docs.python.org/3/objects.inv

nav:
  - 主页: index.md
  - 指南:
    - Logging: logging.md
    - Session: session.md
    - 凭证（Cookie）: credential.md
  - API 示例:
    - 登录: examples/login.md
    - 搜索: examples/search.md
    - 歌曲: examples/song.md
    - 用户: examples/user.md
  - API 文档:
    - 核心(Core):
      - client: api/core/client.md
      - request: api/core/request.md
      - exceptions: api/exceptions.md
      - versioning: api/core/versioning.md
    - 模块(Modules):
      - album: api/album.md
      - comment: api/comment.md
      - login: api/login.md
      - lyric: api/lyric.md
      - mv: api/mv.md
      - search: api/search.md
      - singer: api/singer.md
      - song: api/song.md
      - songlist: api/songlist.md
      - top: api/top.md
      - user: api/user.md
    - 模型(Models):
      - credential: api/models/credential.md
    - 算法(Algorithms):
      - sign: api/algorithms/sign.md
      - tripledes: api/algorithms/tripledes.md
    - 工具(Utils):
      - common: api/utils/common.md
      - qimei: api/utils/qimei.md
  - 帮助:
    - 贡献指南: contributing.md
    - 编写指南: coding.md
  - Release Notes: release-notes.md
