name: Generate Changelog

on:
  push:
    branches:
      - "main"

jobs:
  changelog:
    name: Generate changelog
    if: github.actor != 'github-actions[bot]' && !startsWith(github.event.head_commit.message, '🧹 chore(release-notes):') && !startsWith(github.event.head_commit.message, 'chore(release-notes):')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate release-notes
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --strip all
        env:
          OUTPUT: docs/release-notes.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Detect changes
        id: changes
        run: |
          if git diff --quiet -- docs/release-notes.md; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit
        if: steps.changes.outputs.changed == 'true'
        run: |
          git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          set +e
          git add docs/release-notes.md
          git commit -m "🧹 chore(release-notes): 更新 release notes"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
